### PR TITLE
CORE-966 Support underscores as numeric separators

### PR DESCRIPTION
**Pull request by erer1243**
This implementation seems a little too simple to be correct. I just added underscores to digit characters, and strip them out after lexing. However, it works as far as I have tested. Numbers with underscores work, token location information is correct, underscores at the start of a number do not work (as intended).

### CODE REVIEW

**Review by jeapostrophe — COMMENTED** [review]
I would investigate whether normal JS considers _1 to be a number or an identifier.

You've only changed the tokenizer, but the original spec seems to change the grammar https://tc39.es/proposal-numeric-separator/

**Comment by erer1243** [comment]
commit message has comment

**Review by jeapostrophe — COMMENTED** [review]
This looks good to me, I'd like @DanBurton to double check and tell you how to modify #reach-lang to actually use this version (and you'll make a companion PR over there with examples/test-cases/doc changes)

**Review by DanBurton — APPROVED** [review]

**Comment by DanBurton** [comment]
lgtm. As for modifying reach-lang, we already use our own fork of `language-javascript`, which I think you've already noticed because you made this PR onto the `reach-1` branch. Just update the commit hash in `stack.yaml` and we should be good to go.

Tangential remark: be sure not to rewrite the git history of `reach-1` such that the commit it currently references disappears, in case we want to revert back to that commit for some reason. (If you simply merge this PR, that will not happen. I'm just saying this in general, because in the future we might want to pull in new updates from language-javascript upstream, and if we do so, we should create a new branch so that we can rebase our patches without losing the old commits.)

**Pull request merged**
